package main

// The mined corpus: comments harvested from repositories that took no part in
// writing corpus.go, labelled by hand, and cut in two. This half fits the
// directions and the thresholds. The other half is the held-out set in
// heldout_test.go, which nothing fits from and which is the only honest report
// of what the fit is worth.
//
// It exists because hand-written exemplars put a threshold where hand-written
// prose lives, and that is not where real comments live. Fitted from corpus.go
// alone, the history class scored every one of 229 real comments below its own
// threshold and fired on nothing at all.

var mined = map[string][]string{
	"compat": {
		"legacy alias kept for callers that have not migrated their import path yet",
		"the key is kept under its old name for backward compatibility with persisted user settings",
		"fetch the raw files; kept for the spec resolver",
		"the doctor path still needs the legacy client, so keep that lookup contained here",
		"migrate the old reasoning content to thinking, dropping the invalid legacy blocks",
		"handle the legacy encodings as well as the current one",
		"this type is exposed for migration tooling that reads the upstream format directly",
		"the old role name is mapped onto the current one",
	},
	"tautology": {
		"convert to YAML for storage",
		"wait for all threads to complete",
		"read the file directly",
		"remove the directory if it already exists",
		"check the permission levels",
		"convert to an array and sort by date",
		"save to the downloads directory",
		"write all the values",
		"log the decoded outcome",
		"collect the contiguous change ranges",
		"render the item's inline content and any nested blocks",
		"Name returns the tool name",
		"an Unsubscriber represents something that can be unsubscribed",
		"find the drafts and sent folder ids",
		"upload the blob if content was provided",
	},
	"narrative": {
		"it resolves an optional template, unions the template's grants with the explicit flags, reconciles the validity window, mints with the library, and persists both the new record and the issuance",
		"it swaps the allowlist entry from the old identifier to the new one, marks the superseded issuance revoked, records the new issuance, and re-mints each live credential beneath it",
		"the handler receives the event, resolves the identity, and writes the result back onto the response",
		"we build the request, send it, read the stream line by line, and assemble the accumulated partial content at the end",
		"step one resolves the file id to a path, step two downloads the raw bytes",
		"this works by iterating over every entry and applying the transform to each one",
	},
	"": {
		"implementations must be safe for concurrent use and may be backed by memory or shared storage",
		"names are asserted by their issuer, and nothing at issuance checks uniqueness",
		"it does not check expiry or membership; the layer above adds those so callers get precise errors",
		"the nonce is retained for twice the skew window, the longest a replay could still land inside a valid timestamp",
		"a token not self-signed by the anchor poisons the verifier, so every request fails rather than silently skipping policy",
		"an anchor token does not combine with a keyring: the entries carry the policy",
		"retrieval never requires registration; this only moves malformed-extension failures to authentication time",
		"the two headers carry the chain detached from the token itself, so no single header grows large",
		"header field names carrying the credential on each request",
		"an empty source list means any status in the vocabulary",
		"the registry is the only authority on which statuses a kind may carry and how it may move between them",
		"it is a variable rather than a literal so tests can register synthetic entries; the binary's own set is fixed at startup",
		"the callers read this to gate the operation rather than hardcoding the kind",
		"every check here runs identically whether this is a dry run or not, so a dry run fails on exactly what a real run would",
		"a reference whose number is outside the map is left untouched",
		"validation runs before any mutation, so a malformed input fails closed without burning identifiers",
		"embedded in a longer path; leave it untouched",
		"is postponed-only metadata",
		"an open entry carries neither a reason nor a closed date: both land at close",
		"every replacement is matched against the original content, not incrementally",
		"a validation failure reports the failing index and leaves the file unchanged",
		"the second return value is the matched path, the third reports whether any decision was found",
		"missing or malformed files are non-fatal and return an empty map with a nil error",
		"returns the keys bound to an action, or nil if none",
		"if the migrated identifier already exists in the config, the older entry is discarded",
		"the returned source indicates which rule applied",
		"the caller owns the send side of the channel: it must only receive from it and must never close it",
		"the caller can detect teardown via a receive returning the zero value",
		"stop delivery first so nothing new lands in the buffer",
		"the ordering is the anchor first, then the account, then the user",
		"resolution runs file-relative first, then relative to the register root",
		"the value must be valid JSON, the name must not collide with a built-in, and a duplicate name is rejected",
		"the payload is returned byte for byte, so the wire claim is exactly what was provided",
		"a name set more than once is an error",
		"single writer by construction: one connection, held for life",
		"the header region ends at the first band heading",
		"hidden directories are not descended into",
		"log only the state transitions, not every round",
		"the trigger's own close counts as the first application",
		"no credential is needed here, so the parent's pre-run hook is overridden",
		"the writer the status line is printed to",
		"poll the measurement endpoint until the measurement leaves the in-progress state",
		"it evaluates the condition tree against the input and returns whether it succeeded",
		"a broken tree is not evidence of a comment",
		"a custom check that runs after the chain is verified and possession proven",
		"the container version is emitted as a header line and checked on parse, independent of the wire version",
		"the validity window is long enough for delivery latency and drift, short enough to bound capture exposure",
		"an empty audience is a no-op",
		"attribute the failure before evicting: only a chainless token leaves the cached entry as the suspect",
		"the receiver does not know our chain: retransmit once with the chain detached alongside the same still-valid token",
		"development-only allowlist that accepts everything",
		"the label falls back to the public key when the token carries no name",
		"the pinned public key remains the trust anchor",
		"changing this would orphan existing installations",
		"the newer models reject the older shape and require the adaptive one",
		"the editor is chosen from the dedicated variable, then the visual one, then the generic one",
		"this data feeds the request waterfall",
		"the transport owns this field and fills it from the incoming request; a mismatch fails the signature",
		"requests without a signature pass only when the effective token is a bearer one",
		"registering the type only moves malformed payload failures earlier",
		"the signatures are checked here, and the trust is established per request",
		"it fails if the store already holds a live anchor",
		"depositing the identifier in the allowlist is the command layer's job",
		"the allowlist keys on the account identifier, so minting a user generation does not touch it",
		"the caller confirms before calling",
		"the store holds exactly one anchor, so this is the store's own name",
		"scaffolding rather than records: never imported",
		"the parser is idempotent on an already-valid stem: it only bites when the stem is too long",
		"the runtime renders its own banner, so an imported hand banner would duplicate it",
		"the substitution never adds or removes lines, so both sides always carry the same line count",
		"computed once so the two paths never compute it differently",
		"it does not use the general-purpose renderer; the implementation is written directly against the styling primitives",
		"the description is a heading level or a list depth",
		"every replacement must match a unique, non-overlapping region of the original",
		"the current working directory is used when the argument is empty",
		"the empty event is the operator-driven move; every other event names the behavior whose cascade writes a status",
	},
}
