package main

import (
	"strings"

	"github.com/mikluko/slopguard/internal/comment"
	"github.com/mikluko/slopguard/internal/corpus"
	"github.com/mikluko/slopguard/internal/lang"
)

// endured is how many later commits have to have touched a file before the
// comments standing in it count as having survived anything.
//
// The number is what separates the positive label from an accident. A comment
// in a file nobody has opened since it was written was never left alone, it was
// never read; a comment still there after this many edits to the same file is
// one that many readings declined to delete.
const endured = 8

// readable returns the paths at HEAD this harvest can parse, in the order git
// lists them.
func readable(dir string) ([]string, error) {
	out, err := corpus.Git(dir, "ls-files")
	if err != nil {
		return nil, err
	}
	var paths []string
	for _, path := range corpus.Lines(out) {
		if !skip(path) && lang.Lookup(path) != nil {
			paths = append(paths, path)
		}
	}
	return paths, nil
}

// survived returns the comments standing in path at HEAD that outlived at least
// [endured] later commits to the same file.
//
// The label is the inverse of a deletion and comes from the same place: every
// author who edited this file since had the comment in front of them and left
// it there. It is weaker evidence than a deletion, which is one person's
// explicit act, and the row carries the count so a reading can weight it.
func survived(dir string, repo Repo, path string, store *corpus.Blobs) ([]corpus.Row, error) {
	language := lang.Lookup(path)
	src, err := store.Read("HEAD:" + path)
	if err != nil || len(src) == 0 || len(src) > maxFile {
		return nil, err
	}
	comments, release := comment.ScanAll(src, language)
	defer release()
	if len(comments) == 0 {
		return nil, nil
	}

	// Merges left out, for the reason the deleted side already leaves them out:
	// a merge carries its side's changes a second time and changed nothing
	// itself, so counting it toward exposure meets the threshold with no work.
	history, err := corpus.Git(dir, "log", "--no-merges", "--format=%H", "--", path)
	if err != nil {
		return nil, err
	}
	// Newest first, so a commit's index is how many later ones touched the file.
	later := map[string]int{}
	for i, sha := range corpus.Lines(history) {
		later[sha] = i
	}
	if len(later) <= endured {
		return nil, nil
	}

	credit, err := corpus.Blame(dir, "", path)
	if err != nil {
		return nil, nil
	}

	// Blanked, like the deleted side. Storing raw code here and blanked code
	// there made `annotates` two different measurements wearing one name:
	// comment markers appeared in 25.2% of survived rows and 4.3% of deleted
	// ones, which is a label anything reading the field could separate on.
	blanked := bare(src, comments)

	var rows []corpus.Row
	for _, one := range comments {
		at := int(one.Line) - 1
		if at < 0 || at >= len(credit) {
			continue
		}
		born := credit[at]
		edits, known := later[born.SHA]
		if !known || edits < endured || !corpus.Prose(corpus.Flat(one.Text)) {
			continue
		}
		// The same floor the deleted side applies. Tested there only, it held on
		// 540 survived rows and zero deleted ones, so `len(annotates) < 40` was a
		// zero-error label for the negative class.
		if one.Annotates == nil || len(spans(blanked, one.Annotates)) < annotatedFloor {
			continue
		}
		row := corpus.Row{
			Repo:       repo.Name,
			License:    repo.License,
			Path:       path,
			Language:   language.Name,
			Label:      corpus.Survived,
			Text:       one.Text,
			Body:       one.Body,
			Added:      born.SHA,
			AddedAt:    born.When,
			Doc:        one.Doc,
			Trailing:   one.Trailing,
			Buried:     one.Buried,
			Lines:      len(one.Nodes),
			Line:       one.Line,
		}
		row.Annotates = corpus.Truncate(spans(blanked, one.Annotates), 400)
		row.CodeFrom = one.Annotates.StartPosition().Row + 1
		row.CodeTo = one.Annotates.EndPosition().Row + 1
		rows = append(rows, row)
	}
	return rows, nil
}

// stride returns the step that takes at most want items evenly across n, so a
// sample spreads over a repository's whole tree rather than over whichever
// directory git happens to list first.
//
// Rounded up. `n/want` gives a step of one whenever n is between want and twice
// want, which walks the whole list and overshoots the cap.
func stride(n, want int) int {
	if want <= 0 || n <= want {
		return 1
	}
	return (n + want - 1) / want
}

// clean reports whether a comment's prose is worth carrying into the corpus at
// all. A licence header is the same text in every file of a repository and
// would dominate any centroid it landed in.
func clean(text string) bool {
	lower := strings.ToLower(text)
	for _, boilerplate := range []string{
		"licensed under the apache license",
		"permission is hereby granted, free of charge",
		"redistribution and use in source and binary forms",
		"this program is free software",
		"copyright (c)",
		"all rights reserved",
		"code generated by",
		"do not edit",
		"spdx-license-identifier",
	} {
		if strings.Contains(lower, boilerplate) {
			return false
		}
	}
	return true
}
