package prose

import (
	"strings"
	"testing"
)

// The marker list is ordered longest first, and a marker that is a prefix of
// another is what that ordering exists for.
func TestStrip(t *testing.T) {
	for _, c := range []struct{ line, want string }{
		{"// the caller holds the lock", "the caller holds the lock"},
		{"/// a rust doc line", "a rust doc line"},
		{"//! an inner rust doc", "an inner rust doc"},
		{"# a shell comment", "a shell comment"},
		{"#!/usr/bin/env bash", "/usr/bin/env bash"},
		{"-- a sql comment", "a sql comment"},
		{"/* a block opener */", "a block opener"},
		{" *  a continuation line", "a continuation line"},
		{`"""Double v."""`, "Double v."},
		{`r"""a raw docstring"""`, "a raw docstring"},
		{"'''a single-quoted docstring'''", "a single-quoted docstring"},
		{"", ""},
		{"//", ""},
		{"no marker at all", "no marker at all"},
		// The closing and opening lines of a block comment carry nothing but
		// markers, and used to keep half of one: `*/` lost its star to the
		// continuation marker and kept the slash, `/**` kept the star.
		{"*/", ""},
		{" */", ""},
		{"**/", ""},
		{"/**", ""},
		{"/** a javadoc opener", "a javadoc opener"},
		{" * a continuation ending the block */", "a continuation ending the block"},
	} {
		if got := Strip(c.line); got != c.want {
			t.Errorf("Strip(%q) = %q, want %q", c.line, got, c.want)
		}
	}
}

// One marker is removed, not every marker: a commented-out comment keeps the
// inner one, which is what tells the rules it was code.
func TestStripRemovesOneMarker(t *testing.T) {
	if got := Strip("// // timeout = 5"); got != "// timeout = 5" {
		t.Errorf("Strip stripped past the first marker: %q", got)
	}
}

// Anchored to the start of a line, so prose that mentions a licence is not one.
func TestNotice(t *testing.T) {
	for _, c := range []struct {
		body string
		want bool
	}{
		{"Copyright 2009 The Go Authors. All rights reserved.", true},
		{"SPDX-License-Identifier: BSD-3-Clause", true},
		{"Licensed under the Apache License, Version 2.0", true},
		{"get the copyright year from the header", false},
		{"the file this reads is licensed under a notice we preserve", false},
		{"double returns v twice over.", false},
		{"", false},
	} {
		if got := Notice(c.body); got != c.want {
			t.Errorf("Notice(%q) = %v, want %v", c.body, got, c.want)
		}
	}
}

// The FreeBSD libm headers Go carries open with a description and reach their
// notice several lines in, so the match cannot be anchored to the comment.
func TestNoticeFoundBelowTheFirstLine(t *testing.T) {
	body := "\n" +
		"__ieee754_log(x)\n" +
		"Return the logarithm of x\n" +
		"\n" +
		"Copyright (C) 1993 by Sun Microsystems, Inc. All rights reserved.\n" +
		"\n" +
		"Permission to use, copy, modify, and distribute this software\n"
	if !Notice(body) {
		t.Error("a notice five lines into a comment went unrecognised")
	}
}

// Indented differs from Strip in exactly one way: what follows the marker keeps
// its shape, so a commented-out block still parses as one.
func TestIndented(t *testing.T) {
	for _, c := range []struct{ line, want string }{
		{"  # resources:", "resources:"},
		{"  #   limits:", "  limits:"},
		{"\t//     cpu: 100m", "    cpu: 100m"},
		{"# ", ""},
		{"#", ""},
		{"  /* var x = 1 */", "var x = 1 "},
	} {
		if got := Indented(c.line); got != c.want {
			t.Errorf("Indented(%q) = %q, want %q", c.line, got, c.want)
		}
	}
}

func TestDedent(t *testing.T) {
	for _, c := range []struct{ text, want string }{
		{"    a\n      b\n    c", "a\n  b\nc"},
		{"a\n  b", "a\n  b"},
		{"    a\n\n    b", "a\n\nb"},
		{"", ""},
		{"   ", "   "},
	} {
		if got := Dedent(c.text); got != c.want {
			t.Errorf("Dedent(%q) = %q, want %q", c.text, got, c.want)
		}
	}
}

// A blank line has no indentation and must not be read as sharing none, or a
// docstring with a paragraph break dedents by nothing at all.
func TestDedentIgnoresBlankLines(t *testing.T) {
	if got := Dedent("    first\n\n    second"); got != "first\n\nsecond" {
		t.Errorf("a blank line set the shared indent: %q", got)
	}
}

func TestDirective(t *testing.T) {
	for _, c := range []struct {
		line string
		want bool
	}{
		{"#!/usr/bin/env bash", true},
		{"//go:generate stringer -type=Kind", true},
		{"// +build linux", true},
		{"//nolint:gocyclo", true},
		{"// Deprecated: use Double.", true},
		{"// eslint-disable-next-line", true},
		{"# noqa: E501", true},
		{"# pragma: no cover", true},
		{"# Generated by Django 4.2.7 on 2024-01-15", true},
		{"// https://go.dev/ref/spec#Expression_statements", true},
		{`# {"$imagepolicy": "flux-system:podinfo"}`, true},
		{"// the caller must hold the lock", false},
		{"# replicas: 3", false},
		{"", false},
	} {
		if got := Directive(c.line); got != c.want {
			t.Errorf("Directive(%q) = %v, want %v", c.line, got, c.want)
		}
	}
}

// PEP 263 writes its encoding line with dashes on both sides, and the dashes
// go with the markers, so what the prefix list has to carry is what survives
// that trim rather than what was written.
func TestDirectiveEncodingLine(t *testing.T) {
	if !Directive("# -*- coding: utf-8 -*-") {
		t.Error("the PEP 263 encoding line read as prose")
	}
}

// Padded on both ends, which is what lets a caller match a phrase as words by
// searching for it with its spaces.
func TestNormalize(t *testing.T) {
	for _, c := range []struct{ text, want string }{
		{"Kept for backwards compatibility.", " kept for backwards compatibility "},
		{"v1/v2 clients", " v1 v2 clients "},
		{"   ", " "},
		{"", " "},
	} {
		if got := Normalize(c.text); got != c.want {
			t.Errorf("Normalize(%q) = %q, want %q", c.text, got, c.want)
		}
	}
	if h := Normalize("this is kept for compatibility"); !strings.Contains(h, " kept for ") {
		t.Errorf("a phrase did not match as words: %q", h)
	}
	// The padding is what stops a phrase from matching inside a longer word.
	if h := Normalize("overkept forwards"); strings.Contains(h, " kept for ") {
		t.Errorf("a phrase matched across word boundaries: %q", h)
	}
}

// The cases a full stop does not end a sentence in: an abbreviation, an
// initial, a version number, and a following word that carries on in lower
// case.
func TestSentences(t *testing.T) {
	for _, c := range []struct {
		text string
		want int
	}{
		{"double returns v twice over.", 1},
		{"double returns v twice over. It panics when v overflows.", 2},
		{"no terminator at all", 0},
		{"a list, e.g. this one, is not two sentences.", 1},
		{"see R. Smith for the derivation.", 1},
		{"needs Go 1.21. or newer", 0},
		{"Ends here! And here? Yes.", 3},
		{"", 0},
	} {
		if got := Sentences(c.text); got != c.want {
			t.Errorf("Sentences(%q) = %d, want %d", c.text, got, c.want)
		}
	}
}

func TestSplit(t *testing.T) {
	for _, c := range []struct {
		text string
		want []string
	}{
		{"One. Two.", []string{"One.", "Two."}},
		{"Only one.", []string{"Only one."}},
		{"a\n   b", []string{"a b"}},
		{"", nil},
	} {
		got := Split(c.text)
		if len(got) != len(c.want) {
			t.Errorf("Split(%q) = %q, want %q", c.text, got, c.want)
			continue
		}
		for i := range got {
			if got[i] != c.want[i] {
				t.Errorf("Split(%q)[%d] = %q, want %q", c.text, i, got[i], c.want[i])
			}
		}
	}
}

// Sentences counts terminators and Split returns pieces, so text that trails
// off unterminated has one more piece than it has sentences. A caller reading
// either as the other is off by one on exactly the comments that do not end in
// a full stop, which is most of the one-liners in any codebase.
func TestSplitCountsOneMoreWhenUnterminated(t *testing.T) {
	for _, text := range []string{
		"double returns v twice over. it is not checked",
		"multiply it by two",
		"One. Two.",
		"",
	} {
		pieces, count := len(Split(text)), Sentences(text)
		if strings.HasSuffix(strings.TrimSpace(text), ".") || text == "" {
			if pieces != count {
				t.Errorf("%q: %d pieces against %d sentences", text, pieces, count)
			}
			continue
		}
		if pieces != count+1 {
			t.Errorf("%q: %d pieces against %d sentences, want one more", text, pieces, count)
		}
	}
}

func TestOpening(t *testing.T) {
	long := []string{"one", "two", "three", "four", "five"}
	if got := Opening(long); len(got) != 3 {
		t.Errorf("Opening kept %d sentences, want 3", len(got))
	}
	short := []string{"one", "two"}
	if got := Opening(short); len(got) != 2 {
		t.Errorf("Opening shortened a comment that was already short: %q", got)
	}
	if got := Opening(nil); got != nil {
		t.Errorf("Opening(nil) = %q", got)
	}
}

func TestCode(t *testing.T) {
	for _, c := range []struct {
		text string
		want bool
	}{
		{"timeout = 5", true},
		{"replicas: 3}", true},
		{"f();", true},
		{"return v * 2", true},
		{"def double(v)", true},
		{"import os", true},
		{"if (ok)", true},
		{"the caller must hold the lock", false},
		{"multiply it by two", false},
		{"", false},
	} {
		if got := Code(c.text); got != c.want {
			t.Errorf("Code(%q) = %v, want %v", c.text, got, c.want)
		}
	}
}

// A keyword decides only where it opens the line. Prose that uses one as an
// ordinary word is prose, and English opens sentences with "if" and "for"
// often enough that reading them anywhere would exempt nothing.
func TestCodeReadsTheFirstWordOnly(t *testing.T) {
	if Code("the type of v is not checked here") {
		t.Error("a keyword in the middle of a sentence read as code")
	}
}
