package rule

import (
	"strings"
	"testing"

	"github.com/mikluko/slopguard/internal/comment"
	"github.com/mikluko/slopguard/internal/model"
)

// Python is the language where prose parses, so its half of the
// commented-out-code rule reads the shape of the statement rather than the fact
// of a clean parse. These are the two sides of that: settings somebody switched
// off, and Django comments that carry an equals sign and are sentences.
//
// The docstring rows are here for the other reason Python is its own case. A
// docstring sits inside the body it documents rather than above it, so the
// declaration every doc rule measures against is the node around the comment
// instead of the node after it.
var pythonCases = []struct {
	name string
	src  string
	want string
}{
	{
		name: "comment restating the code",
		src: `def double(v):
    # multiply it by two
    return v * 2
`,
		want: "restates what the code",
	},
	{
		name: "module comment",
		src: `# Timeouts are in seconds.
TIMEOUT = 5
`,
	},
	{
		name: "a setting switched off",
		src: `# TIMEOUT = 30
TIMEOUT = 5
`,
		want: "commented-out code",
	},
	{
		name: "a call switched off",
		src: `def save(user):
    # user.save()
    return user
`,
		want: "commented-out code",
	},
	{
		// `in` is an operator, so this is a clean parse of an assignment whose
		// right side is a comparison: a sentence wearing an equals sign.
		name: "a settings comment that parses as an assignment",
		src: `# DEBUG=False in production
DEBUG = True
`,
	},
	{
		name: "a field comment that parses as an assignment",
		src: `class Order(models.Model):
    # on_delete=CASCADE is deliberate: an order without a customer is meaningless
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
`,
	},
	{
		name: "docstring padded past its contract",
		src: `def double(v):
    """Double v.

    This function takes a value and returns a value. The implementation is
    simple and should be easy to read.
    """
    return v * 2
`,
		want: "padded documentation",
	},
	{
		name: "docstring stating a contract",
		src: `def save(order):
    """Persist the order, raising when the customer is gone."""
    order.save()
`,
	},
	{
		name: "coverage pragma",
		src: `def unreachable():  # pragma: no cover
    raise NotImplementedError
`,
	},
	{
		name: "migration header",
		src: `# Generated by Django 4.2.7 on 2024-01-15 10:23
from django.db import migrations
`,
	},
}

func TestPython(t *testing.T) {
	for _, c := range pythonCases {
		t.Run(c.name, func(t *testing.T) {
			if model.Speaks(c.want) {
				skipWithoutRuntime(t)
			}
			findings := scan([]byte(c.src), python, []comment.Span{{Start: 0, End: uint(len(c.src))}})
			switch {
			case c.want == "" && len(findings) > 0:
				t.Fatalf("nudged an acceptable comment: %s", findings[0].Reason)
			case c.want == "":
			case len(findings) == 0:
				t.Fatalf("missed a comment that should carry %q", c.want)
			case !strings.Contains(findings[0].Reason, c.want):
				t.Fatalf("reason %q does not carry %q", findings[0].Reason, c.want)
			}
		})
	}
}
